// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230609141954_DatosVillas01")]
    partial class DatosVillas01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Amenidad = "Zoo",
                            Area = 50,
                            Detalle = "cabañas, naturaleza",
                            FechaActualizacion = new DateTime(2023, 6, 9, 9, 19, 54, 487, DateTimeKind.Local).AddTicks(2730),
                            FechaCreacion = new DateTime(2023, 6, 9, 9, 19, 54, 487, DateTimeKind.Local).AddTicks(2715),
                            ImagenUrl = "",
                            Nombre = "Villa Real",
                            Tarifa = 150.0
                        },
                        new
                        {
                            id = 2,
                            Amenidad = "Mar",
                            Area = 70,
                            Detalle = "cabañas, mar",
                            FechaActualizacion = new DateTime(2023, 6, 9, 9, 19, 54, 487, DateTimeKind.Local).AddTicks(2735),
                            FechaCreacion = new DateTime(2023, 6, 9, 9, 19, 54, 487, DateTimeKind.Local).AddTicks(2734),
                            ImagenUrl = "",
                            Nombre = "Villa Nueva",
                            Tarifa = 180.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
